In [10]:
import tensorflow as tf
import numpy as np
import pandas as pd 

# Learning XOR Logic Gate

In [84]:
# data for XOR gate
X = np.array([[0,0,1,1], [0,1,0,1]], dtype=np.float32)
y = np.array([0,1,1,0], dtype=np.float32)
y
# X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=np.float32)
# y.reshape(1,-1)

array([0., 1., 1., 0.], dtype=float32)

In [50]:
X

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [85]:
y.shape

(4,)

In [68]:
X.shape

(2, 4)

In [99]:
# hyperparameters
lr = None   # learning rate
arch = [2,6] # architecture
epochs = 1

model = Model(arch)

# train model
for epoch in range(epochs):
    # creating a feedforward model
    y_pred = model(X)

#     with tf.GradientTape() as g:
#         loss = model.loss(y_pred, y_true=y)
    
#     grad = g.gradient(loss, model.Variable)
#     print(grad)
    
    
#     print(f"epoch: {epoch:4d} \tloss: {loss:.4f}")

layer1_w.shape     = (2, 2)
X.shape            = (2, 4)
a1.shape           = (2, 4)
layer1_bias.shape  = (2, 1)

layer2_w.shape     = (6, 2)
a1.shape           = (2, 4)
a2.shape           = (6, 4)
layer2_bias.shape  = (6, 1)

layer3_w.shape     = (1, 6)
a2.shape           = (6, 4)
a3.shape           = (1, 4)
layer3_bias.shape  = (1,)



In [97]:
class Model:
    def __init__(self, arch):
        self.arch = arch
        self.built = False # the model is called for first time
        
    
    """
    Init weight and biases for various layers of nodes
    args = no. of feature of X (in this case, 2)"""
    def build(self, features_len):
        w_init = tf.random.normal # alias for tf.random.normal
        b_init = tf.zeros         # alias for tf.zeros
        
        # init wt and bias for l1 [10 neurons]
        self.layer1_w = tf.Variable(
            w_init(shape=(self.arch[0], features_len)))
        self.layer1_bias = tf.Variable(
            w_init(shape=(self.arch[0], 1))) # 1 coz not a matrix
        
        # init wt and bias for l2 [10 neurons]
        self.layer2_w = tf.Variable(
            w_init(shape=(self.arch[1], self.arch[0])))
        self.layer2_bias = tf.Variable(
            w_init(shape=(self.arch[1], 1))) # 1 coz not a matrix
        
        # init wt and bias for l3 [1 neuron]
        self.layer3_w = tf.Variable(
            w_init(shape=(1, self.arch[1])))
        self.layer3_bias = tf.Variable(
            w_init(shape=(1,))) # 1 coz not a matrix
        
        self.Variable = [self.layer1_w, self.layer2_w, self.layer3_w, 
                         self.layer1_bias, self.layer2_bias, self.layer3_bias]

        
    """feedfwd process
    recieve X.shape = (2,4) -> 2 features, 4 samples
    return  y.shape = (1,4) -> 1 output, 4 samples
    """
    def __call__(self, X):
        if self.built == False:
            self.build(X.shape[0])
            self.built = True
        
        # layer 1 feedfwd
        print(f"layer1_w.shape     = {self.layer1_w.shape}")
        print(f"X.shape            = {X.shape}")
        z1 = tf.matmul(self.layer1_w, X) + self.layer1_bias
        a1 = tf.math.sigmoid(z1)
        print(f"a1.shape           = {a1.shape}")
        print(f"layer1_bias.shape  = {self.layer1_bias.shape}\n")
        
        # layer 2 feedfwd
        print(f"layer2_w.shape     = {self.layer2_w.shape}")
        print(f"a1.shape           = {a1.shape}")
        z2 = tf.matmul(self.layer2_w, a1) + self.layer2_bias
        a2 = tf.math.sigmoid(z2)
        print(f"a2.shape           = {a2.shape}")
        print(f"layer2_bias.shape  = {self.layer2_bias.shape}\n")
        
        # layer 3 feedfwd
        print(f"layer3_w.shape     = {self.layer3_w.shape}")
        print(f"a2.shape           = {a2.shape}")
        z3 = tf.matmul(self.layer3_w, a2) + self.layer3_bias
        a3 = tf.math.sigmoid(z3)
        print(f"a3.shape           = {a3.shape}")
        print(f"layer3_bias.shape  = {self.layer3_bias.shape}\n")
        return a3
        
        
    
    def loss(self, y_pred, y_true):
        return tf.reduce_sum((y_pred - y_true)**2) / 4 # no. of rows
    

In [59]:
a = tf.random.uniform(shape=(3,2), minval=1, maxval=5, dtype=tf.int32)
tf.print(a)

[[4 3]
 [1 1]
 [1 1]]


In [60]:
b = tf.random.uniform(shape=(2,4), minval=1, maxval=5, dtype=tf.int32)
tf.print(b)

[[2 2 2 2]
 [1 4 4 1]]


In [61]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[11, 20, 20, 11],
       [ 3,  6,  6,  3],
       [ 3,  6,  6,  3]])>